export const ADMIN_TOOLTIPS: Record<string, string> = {
  // Patient form
  first_name: "Patient's legal first name as it appears on their insurance card",
  last_name: "Patient's legal last name as it appears on their insurance card",
  dob: "Date of birth, used to verify Medicare/Medicaid eligibility",
  phone: "Primary contact number for the patient or their caregiver",
  pickup_address: "The patient's home address where the crew picks them up",
  location_type: "Whether the patient's home is a private residence, SNF, or assisted living, affects how the address displays on crew runs",
  facility_id: "The facility where the patient resides, used when home location is not a private residence",
  dropoff_facility: "The facility the patient is transported to",
  weight_lbs: "Patient weight in pounds, required for bariatric equipment determination and safety matrix",
  transport_type: "The type of transport this patient requires, determines PCR documentation requirements and billing codes",
  schedule_days: "Which days of the week this patient has recurring transport scheduled",
  chair_time: "The time the patient needs to be seated at the dialysis facility, used to validate B-leg return pickup time",
  appointment_time: "The scheduled appointment time at the destination facility",
  recurrence_start_date: "The first date this recurring schedule takes effect",
  primary_payer: "The patient's primary insurance, determines HCPCS codes and billing rates",
  member_id: "The patient's insurance member ID number, required for claim submission",
  secondary_payer: "Secondary insurance that pays after the primary. Medicare patients often have Medicaid or supplemental as secondary",
  secondary_member_id: "The patient's secondary insurance member ID number",
  mobility: "How the patient gets around, affects crew preparation and stretcher requirements",
  trips_per_week_limit: "Soft cap on one-way legs per calendar week (each direction is one leg, so a round-trip dialysis day counts as 2). Used to flag over-scheduling before it hits payer frequency limits. Advisory only, does not block scheduling.",
  stairs_required: "Whether the crew will encounter stairs at pickup or dropoff, affects crew preparation",
  special_equipment: "Any special equipment required for this patient's transport",
  oxygen_lpm: "Oxygen flow rate in liters per minute if the patient requires supplemental oxygen during transport",
  chair_time_duration: "How long the dialysis treatment runs, used to calculate the earliest valid return pickup time for the B-leg",
  appointment_duration: "Estimated length of the appointment, used for scheduling return pickup",
  stair_chair: "Patient requires a stair chair to navigate stairs at pickup or dropoff",
  oxygen_required: "Patient requires supplemental oxygen during transport, triggers QM billing modifier",
  bariatric: "Patient requires bariatric equipment, triggers QL billing modifier and bariatric rate",
  standing_order: "Physician's signed order on file authorizing recurring transport, separate from the recurring schedule. Upload the signed document under Documents.",
  auth_required: "Prior authorization is required from the payer before transport, claim will be blocked if auth is missing or expired",
  auth_expiration: "The date the current prior authorization expires, system will flag runs after this date",

  // Compliance & Authorization — Phase 3
  prior_auth_utn: "RSNAT Unique Tracking Number issued by the Medicare MAC after an affirmative prior authorization decision. Required per 42 CFR 410.40 for repetitive scheduled non-emergent transports meeting frequency thresholds.",
  prior_auth_period_start: "First date the RSNAT prior authorization covers. Trips before this date are not protected by the auth.",
  prior_auth_period_end: "Last date the RSNAT prior authorization covers. Trips after this date require a new UTN.",
  pcs_signed_date: "Date the physician signed the Physician Certification Statement (PCS). PCS is valid for 60 days per CMS rules; the system will flag expiration automatically.",
  other_payer_auth: "Use for non-Medicare-RSNAT prior authorizations: Medicaid managed care plans, commercial payer pre-auth, or any payer-specific auth requirement that isn't governed by 42 CFR 410.40. For Medicare RSNAT auth, use the RSNAT block above.",
  pcs_physician_npi: "10-digit National Provider Identifier of the physician who signed the PCS. Required by 42 CFR 410.40(d). Found on the PCS form.",
  pcs_physician_name: "Full name of the PCS-signing physician as it appears on the PCS form.",

  // Scheduling
  pickup_time: "The time the crew will arrive to pick up the patient",
  trip_type: "The type of transport for this specific run, determines PCR documentation and billing codes",
  est_duration: "Estimated time from pickup to dropoff in minutes, used for schedule planning",
  one_off_name: "Patient name for this one-time run, does not create a patient record",
  one_off_pickup: "Full pickup address for this one-time run",
  one_off_dropoff: "Full dropoff address for this one-time run",

  // Trucks & Crews
  truck_name: "The unit name or number displayed on crew dashboards and dispatch board",
  vehicle_id: "The physical vehicle identification number, recorded on PCR for billing documentation",
  power_stretcher: "This unit is equipped with a power or bariatric stretcher, required for bariatric patients",
  stair_chair_equip: "This unit carries a stair chair for patients who cannot navigate stairs independently",
  oxygen_mount: "This unit has an oxygen mount, required for patients needing supplemental O₂ during transport",

  // Billing
  base_rate: "The flat transport fee charged to this payer before mileage, corresponds to HCPCS base transport code",
  mileage_rate: "The per-mile rate charged to this payer for loaded miles, corresponds to HCPCS A0425",
  wait_rate: "The per-minute rate charged when crew wait time exceeds the grace window",
  oxygen_fee: "Additional fee charged when oxygen is required during transport. QM modifier",
  extra_attendant: "Additional fee when a second attendant is required beyond standard crew",
  bariatric_fee: "Additional fee for bariatric transports. QL modifier",
  loaded_miles: "Miles driven with the patient on board, from pickup to dropoff",
  est_charge: "Estimated total charge based on base rate plus loaded miles at this payer's rates",
  denial_code: "The payer-issued code explaining why the claim was denied, used for resubmission",
  denial_reason: "Plain language explanation of the denial, reference this when correcting and resubmitting",
  amount_paid: "The amount the payer actually remitted for this claim",

  // Clinical & Billing Defaults — pre-fills the PCR every transport
  icd10_codes_default: "Standing ICD-10 diagnosis codes for this patient, auto-populated from transport type, copied onto every PCR. Edit per encounter if the diagnosis changes.",
  default_chief_complaint: "Default presenting complaint pre-filled on every PCR. NEMSIS eSituation.09. Crew can override per encounter.",
  default_primary_impression: "Default working impression pre-filled on every PCR. NEMSIS eSituation.11. Crew can override per encounter.",
  default_medical_necessity_reason: "Why ambulance transport (vs. wheelchair van or POV) is medically required. Required text on the claim per CMS MBPM Ch. 10.",
  default_bed_confined: "Patient meets all three CMS bed-confinement criteria (unable to get up from bed without assistance, unable to ambulate, unable to sit in a chair/wheelchair).",
  default_cannot_transfer: "Patient cannot safely transfer to a wheelchair or other vehicle, stretcher transport is medically required.",
  default_requires_monitoring: "Patient requires medical monitoring (cardiac, airway, IV titration, restraint observation, etc.) during transport.",
  default_oxygen_transport: "Patient requires supplemental oxygen administration during transport, triggers QM modifier on the claim.",
  default_bh_authorization_type: "Behavioral-health legal authorization type that permits this transport (1013, ER hold, court order, voluntary). Required on every psych transport.",
  default_bh_authorizing_facility: "Facility where the BH authorization was issued, typically the sending ED or psychiatric unit.",
  default_bh_authorizing_physician_name: "Name of the physician who signed the BH authorization.",
  default_bh_authorizing_physician_npi: "10-digit NPI of the physician who signed the BH authorization.",
  default_wound_type: "Default wound classification (pressure ulcer, surgical, diabetic ulcer, etc.), pre-fills wound care PCRs.",
  default_wound_location: "Default anatomic location of the wound (e.g. left heel, sacrum), pre-fills wound care PCRs.",
  default_wound_stage: "Default pressure ulcer / wound stage, pre-fills wound care PCRs.",
};
