project_id = "slyxmgoonugqsnubdrqi"

[functions.crew-run-sheet]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.setup-system-creator]
verify_jwt = false

[functions.company-signup]
verify_jwt = false

[functions.dispatch-intelligence]
verify_jwt = false

[functions.accept-invite]
verify_jwt = false

[functions.create-company]
verify_jwt = false

[functions.validate-invite]
verify_jwt = false

[functions.test-clearinghouse-connection]
verify_jwt = false

[functions.send-claims-sftp]
verify_jwt = false

[functions.retrieve-remittance-sftp]
verify_jwt = false