project_id = "slyxmgoonugqsnubdrqi"

[functions.crew-run-sheet]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.setup-system-creator]
verify_jwt = false

[functions.company-signup]
verify_jwt = false

[functions.dispatch-intelligence]
verify_jwt = false

[functions.accept-invite]
verify_jwt = false

[functions.create-company]
verify_jwt = false

[functions.validate-invite]
verify_jwt = false

[functions.test-officeally-connection]
verify_jwt = false

[functions.send-claims-officeally]
verify_jwt = false

[functions.retrieve-remittance-officeally]
verify_jwt = false

[functions.check-eligibility]
verify_jwt = false

[functions.simulation-lab]
verify_jwt = false

[functions.manage-company]
verify_jwt = false
