project_id = "slyxmgoonugqsnubdrqi"

[functions.crew-run-sheet]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.setup-system-creator]
verify_jwt = false

[functions.company-signup]
verify_jwt = false