import { useSearchParams, Link } from "react-router-dom";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { ArrowLeft } from "lucide-react";

function LegalFooter() {
  return (
    <div className="mt-12 pt-6 border-t border-border text-center text-xs text-muted-foreground">
      <p>© {new Date().getFullYear()} PodDispatch LLC. All rights reserved.</p>
      <p className="mt-1">
        Questions? Contact{" "}
        <a href="mailto:support@poddispatch.com" className="text-primary hover:underline">
          support@poddispatch.com
        </a>
      </p>
    </div>
  );
}

export default function LegalPage() {
  const [searchParams] = useSearchParams();
  const initialTab = searchParams.get("tab") || "terms";

  return (
    <div className="min-h-screen bg-background">
      <div className="mx-auto max-w-3xl px-4 py-8">
        <div className="mb-6">
          <Link
            to="/login"
            className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            <ArrowLeft className="h-4 w-4" /> Back to Login
          </Link>
        </div>

        <h1 className="text-2xl font-bold tracking-tight text-foreground mb-6">
          Legal & Compliance
        </h1>

        <Tabs defaultValue={initialTab}>
          <TabsList className="w-full grid grid-cols-2 md:grid-cols-4 lg:grid-cols-7 h-auto">
            <TabsTrigger value="terms">Terms</TabsTrigger>
            <TabsTrigger value="privacy">Privacy</TabsTrigger>
            <TabsTrigger value="baa">BAA</TabsTrigger>
            <TabsTrigger value="aup">Acceptable Use</TabsTrigger>
            <TabsTrigger value="clearinghouse">Clearinghouse</TabsTrigger>
            <TabsTrigger value="retention">Retention</TabsTrigger>
            <TabsTrigger value="incident">Incident Response</TabsTrigger>
          </TabsList>

          <TabsContent value="terms">
            <article className="prose prose-sm dark:prose-invert max-w-none mt-6">
              <h2>PodDispatch Terms of Service</h2>
              <p className="text-muted-foreground text-sm">Version 2.0 — Last updated April 2026</p>

              <h3>1. The Service</h3>
              <p>PodDispatch LLC provides a software-as-a-service platform for non-emergency medical transportation (NEMT) and basic life support (BLS) ambulance operators. The platform includes dispatch management, crew scheduling, patient run coordination, electronic patient care report (ePCR) documentation, billing claim generation, and 837P EDI file export.</p>

              <h3>2. What PodDispatch Is Not</h3>
              <p>PodDispatch is not a clearinghouse, billing agent, or billing service. PodDispatch does not adjudicate claims, transmit claims directly to payers on behalf of the operator (except where the operator has independently configured a clearinghouse integration under their own trading partner agreement), or provide medical coding, billing, or legal advice.</p>

              <h3>3. Operator Responsibility</h3>
              <p>The operator is the responsible billing party for all claims submitted through or generated by the platform. The operator is solely responsible for the accuracy of all clinical documentation, patient demographics, insurance information, diagnosis codes, HCPCS codes, modifiers, and any other claim data entered into the system. PodDispatch makes no guarantee that claims generated will be accepted or paid by any payer or clearinghouse.</p>

              <h3>4. User Roles and Access Control</h3>
              <p>The platform supports multiple user roles including Owner, Dispatcher, Biller, and Crew. Each operator is responsible for managing access and permissions for their own employees, including provisioning and deprovisioning user accounts, enforcing password and credential hygiene, and ensuring only authorized workforce members access protected health information.</p>

              <h3>5. Account Registration</h3>
              <p>You must provide accurate and complete information when creating an account. The owner-role user who creates the account represents that they have authority to bind the operator company to these terms and to the Business Associate Agreement that is incorporated by reference upon account creation.</p>

              <h3>6. Subscription and Payment</h3>
              <p>PodDispatch is offered on a monthly subscription basis. Payment is due at the beginning of each billing period. Subscriptions automatically renew unless cancelled before the renewal date. Refunds are available within 30 days of initial subscription if you have completed onboarding, run at least one trip through the system, and the software does not perform as described. No refunds are available after 30 days or following account suspension for terms violations.</p>

              <h3>7. HIPAA Compliance</h3>
              <p>You acknowledge that you are a HIPAA covered entity or business associate and that you are responsible for your own HIPAA compliance. PodDispatch executes a Business Associate Agreement with you upon account creation by an owner-role user. You are responsible for ensuring your use of PodDispatch complies with all applicable federal and state privacy and security laws.</p>

              <h3>8. Acceptable Use</h3>
              <p>Your use of the platform is subject to the Acceptable Use Policy, which is incorporated by reference into these terms. PodDispatch LLC reserves the right to suspend or terminate accounts that violate these terms or the Acceptable Use Policy without refund.</p>

              <h3>9. Data Ownership</h3>
              <p>You own all data you enter into PodDispatch including patient records, trip records, and billing information. PodDispatch will not sell your data or use it for any purpose other than providing the service. Upon cancellation you may request an export of your data within 30 days as described in the Data Retention and Deletion Policy.</p>

              <h3>10. Limitation of Liability</h3>
              <p>PodDispatch is provided as is without warranty of any kind. PodDispatch shall not be liable for any indirect, incidental, special, or consequential damages including lost revenue, lost profits, denied claims, or data loss arising from your use of the service. PodDispatch's total liability shall not exceed the fees paid in the three months preceding the claim.</p>

              <h3>11. Indemnification</h3>
              <p>You agree to indemnify and hold harmless PodDispatch LLC and its officers, employees, and agents from any claims, damages, or expenses including reasonable attorneys fees arising from your use of the service, your submission of claim data, or your violation of these terms.</p>

              <h3>12. Modifications</h3>
              <p>PodDispatch reserves the right to modify these terms at any time. You will be notified of material changes by email or in-app notification. Continued use of the service after notification constitutes acceptance of the modified terms.</p>

              <h3>13. Termination</h3>
              <p>PodDispatch may suspend or terminate your account for violation of these terms, the Acceptable Use Policy, non-payment, or any conduct that PodDispatch determines is harmful to other users or to the service. You may cancel your subscription at any time through the account settings.</p>

              <h3>14. Governing Law</h3>
              <p>These terms are governed by the laws of the State of Georgia. Any disputes shall be resolved in the courts of Georgia.</p>

              <h3>15. Contact</h3>
              <p>For questions about these terms contact <a href="mailto:support@poddispatch.com" className="text-primary hover:underline">support@poddispatch.com</a>.</p>
            </article>
          </TabsContent>

          <TabsContent value="privacy">
            <article className="prose prose-sm dark:prose-invert max-w-none mt-6">
              <h2>PodDispatch Privacy Policy</h2>
              <p className="text-muted-foreground text-sm">Version 2.0 — Last updated April 2026</p>

              <h3>Introduction</h3>
              <p>PodDispatch LLC collects and processes protected health information (PHI) on behalf of operator companies as a HIPAA Business Associate. This Privacy Policy describes how we collect, use, retain, and protect information in connection with our platform.</p>

              <h3>PHI We Collect on Behalf of Operators</h3>
              <p>The PHI we collect and process includes patient names, dates of birth, addresses, telephone numbers, insurance member IDs and payer information, ICD-10 diagnosis codes, clinical documentation entered through the ePCR (vitals, narratives, assessments, equipment, signatures), transport records (origin, destination, times, mileage, crew assignments), and billing and claim records.</p>

              <h3>Operator Account Information We Collect Directly</h3>
              <p>We collect operator account information including company name, NPI number, state of operation, owner contact information, employee names and roles, vehicle and equipment records, payer mix, billing configuration, and payment information for the platform subscription.</p>

              <h3>How We Use This Information</h3>
              <p>This information is used solely to provide the platform services described in the Terms of Service and the executed Business Associate Agreement. PodDispatch does not sell PHI, does not use PHI for advertising, and does not use PHI for any purpose other than delivering the contracted service to the operator.</p>

              <h3>How We Protect Information</h3>
              <p>We use industry-standard security measures including encryption in transit (TLS 1.2 or higher) and encryption at rest (AES-256), role-based access controls, audit logging of every PHI access event, and regular security reviews. Patient data is stored in HIPAA-compliant infrastructure. Access to PHI is limited to authorized PodDispatch personnel with a documented operational need.</p>

              <h3>Data Retention</h3>
              <p>PHI is retained for seven years following account termination in accordance with HIPAA requirements unless the operator requests earlier deletion consistent with applicable law. Full retention details are in the Data Retention and Deletion Policy.</p>

              <h3>Operator Data Deletion Requests</h3>
              <p>Operators may request deletion of their company data by contacting PodDispatch LLC directly at <a href="mailto:support@poddispatch.com" className="text-primary hover:underline">support@poddispatch.com</a>. Deletion is processed within 60 days as described in the Data Retention and Deletion Policy and is subject to applicable legal-hold requirements.</p>

              <h3>Subprocessors and Infrastructure</h3>
              <p>PodDispatch uses Supabase for data storage, authentication, and serverless function infrastructure. PodDispatch uses Stripe for processing platform subscription payments (no PHI is shared with Stripe). Each subprocessor is bound by appropriate written agreements that protect PHI.</p>

              <h3>Breach Notification</h3>
              <p>Security incidents involving PHI will be reported to affected operators within 60 days of discovery as required by the HIPAA Breach Notification Rule. Operators are responsible for notifying affected patients and the Department of Health and Human Services as required by law. Full procedures are in the Incident Response Policy.</p>

              <h3>Your Rights</h3>
              <p>Operators have the right to access, correct, export, or delete their account data at any time. PHI-related rights are governed by the Business Associate Agreement and the underlying patient relationship between the operator (covered entity) and the patient.</p>

              <h3>Changes to This Policy</h3>
              <p>We may update this Privacy Policy from time to time. We will notify you of material changes by email or in-app notification. Continued use of the service after notification constitutes acceptance of the updated policy.</p>

              <h3>Contact</h3>
              <p>For privacy-related questions contact <a href="mailto:support@poddispatch.com" className="text-primary hover:underline">support@poddispatch.com</a>.</p>
            </article>
          </TabsContent>

          <TabsContent value="baa">
            <article className="prose prose-sm dark:prose-invert max-w-none mt-6">
              <h2>PodDispatch Business Associate Agreement</h2>
              <p className="text-muted-foreground text-sm">Version 2.0 — Effective upon account creation by an owner-role user</p>

              <h3>Parties</h3>
              <p>This Business Associate Agreement ("BAA") is entered into between PodDispatch LLC ("Business Associate") and the operator company identified during account registration ("Covered Entity"). This BAA is incorporated by reference into the PodDispatch Terms of Service and is binding upon account creation by an owner-role user.</p>

              <h3>Definitions</h3>
              <p>Terms used in this BAA shall have the same meanings as defined in the Health Insurance Portability and Accountability Act of 1996 ("HIPAA") and its implementing regulations at 45 CFR Parts 160 and 164. "Protected Health Information" or "PHI" means any individually identifiable health information created, received, maintained, or transmitted by Business Associate on behalf of Covered Entity through the platform.</p>

              <h3>Obligations of PodDispatch LLC (Business Associate)</h3>
              <p>PodDispatch LLC agrees to:</p>
              <ul>
                <li>Use PHI only as necessary to provide platform services described in the Terms of Service.</li>
                <li>Implement appropriate administrative, physical, and technical safeguards to protect PHI in accordance with 45 CFR Part 164 Subpart C.</li>
                <li>Report security incidents and breaches of unsecured PHI to the Covered Entity within 60 days of discovery.</li>
                <li>Ensure that any subcontractors who create, receive, maintain, or transmit PHI on Business Associate's behalf agree in writing to the same restrictions and obligations that apply to Business Associate under this BAA.</li>
                <li>Make PHI available to the Covered Entity as necessary to satisfy Covered Entity's obligations under 45 CFR 164.524 (right of access).</li>
                <li>Make Business Associate's internal practices, books, and records available to the Secretary of Health and Human Services for purposes of determining compliance with HIPAA.</li>
                <li>Return or destroy PHI upon termination of services where feasible. Where return or destruction is not feasible (for example, due to backup infrastructure constraints or legal hold), PHI shall continue to be protected under the terms of this BAA.</li>
              </ul>

              <h3>Obligations of the Operator (Covered Entity)</h3>
              <p>The Covered Entity agrees to:</p>
              <ul>
                <li>Obtain all necessary patient authorizations and consents required under HIPAA before entering PHI into the platform.</li>
                <li>Provide accurate patient information, demographics, insurance, and clinical documentation.</li>
                <li>Not request or instruct PodDispatch to use or disclose PHI in any manner that would not be permissible under HIPAA if done by the Covered Entity directly.</li>
                <li>Notify Business Associate of any limitations in its notice of privacy practices, restrictions, or revocations of authorization that affect Business Associate's permitted uses or disclosures of PHI.</li>
                <li>Manage workforce access to the platform, including provisioning, deprovisioning, and credential hygiene.</li>
              </ul>

              <h3>Permitted Uses and Disclosures</h3>
              <p>Business Associate may use and disclose PHI only as necessary to provide the dispatch, scheduling, ePCR, claim generation, and billing-export services described in the Terms of Service, or for the proper management and administration of Business Associate's own business and to carry out its legal responsibilities. Business Associate shall not use or disclose PHI in any manner that would violate HIPAA if done by the Covered Entity.</p>

              <h3>Security of Electronic PHI</h3>
              <p>Business Associate shall implement administrative, physical, and technical safeguards that reasonably and appropriately protect the confidentiality, integrity, and availability of electronic PHI in accordance with 45 CFR Part 164 Subpart C, including encryption at rest using AES-256 and encryption in transit using TLS 1.2 or higher.</p>

              <h3>Term and Termination</h3>
              <p>This BAA is effective as of the date of account creation. Either party may terminate this BAA if the other party materially breaches a provision and fails to cure the breach within 30 days of written notice. Upon termination, Business Associate shall return or destroy PHI as described above.</p>

              <h3>Breach Notification</h3>
              <p>Business Associate shall notify Covered Entity without unreasonable delay and in no case later than 60 days following discovery of a breach of unsecured PHI. Notification shall identify each individual whose PHI was breached, describe the breach, identify the type of PHI involved, and describe the steps Business Associate has taken to investigate and mitigate the breach. See the Incident Response Policy for full procedures.</p>

              <h3>Limitation of Liability</h3>
              <p>Business Associate's total liability under this BAA shall not exceed the total fees paid by Covered Entity in the three months preceding the event giving rise to the claim.</p>

              <h3>Governing Law</h3>
              <p>This BAA is governed by the laws of the State of Georgia.</p>
            </article>
          </TabsContent>

          <TabsContent value="aup">
            <article className="prose prose-sm dark:prose-invert max-w-none mt-6">
              <h2>PodDispatch Acceptable Use Policy</h2>
              <p className="text-muted-foreground text-sm">Version 1.0 — Effective April 2026</p>

              <h3>Permitted Use</h3>
              <p>Operators and their employees may use PodDispatch only for lawful non-emergency medical transportation (NEMT) and basic life support (BLS) ambulance transport operations and the documentation, dispatch, and billing activities directly related to those operations.</p>

              <h3>Prohibited Activities</h3>
              <p>The following activities are strictly prohibited and may result in immediate account suspension or termination without refund:</p>
              <ul>
                <li><strong>Billing fraud:</strong> Submitting or generating claims for services that were not rendered, were not medically necessary, or were not supported by the documentation in the ePCR.</li>
                <li><strong>False documentation:</strong> Entering false patient demographics, insurance information, diagnosis codes, transport times, mileage, vital signs, signatures, or clinical findings.</li>
                <li><strong>Credential sharing:</strong> Sharing login credentials across multiple individuals. Each workforce member must have their own user account. Shared credentials are a HIPAA violation.</li>
                <li><strong>Cross-tenant access attempts:</strong> Attempting to access, view, modify, or export data belonging to other operator companies on the platform.</li>
                <li><strong>Out-of-scope use:</strong> Using the platform to store data unrelated to medical transport operations, including non-medical business data, personal records, or third-party content.</li>
                <li><strong>Reverse engineering:</strong> Reverse engineering, decompiling, or attempting to extract the platform's proprietary algorithms, billing logic, claim-scoring models, or source code.</li>
                <li><strong>Automated abuse:</strong> Using bots, scrapers, or automated tools to bulk-extract data, overwhelm the platform, or bypass rate limits.</li>
                <li><strong>Security probing without authorization:</strong> Performing penetration testing, vulnerability scans, or other security probing without prior written authorization from PodDispatch LLC.</li>
              </ul>

              <h3>Enforcement</h3>
              <p>PodDispatch LLC monitors platform activity for compliance with this policy. Violations may result in immediate account suspension without refund. PodDispatch LLC cooperates with law enforcement investigations involving fraud, abuse, or HIPAA violations and will produce records as required by valid legal process.</p>

              <h3>Operator Accountability</h3>
              <p>Operators are responsible for the conduct of all users under their account, including employees, contractors, and any other workforce members granted access. The owner-role user is the responsible party for ensuring company-wide compliance with this policy.</p>

              <h3>Reporting Violations</h3>
              <p>Suspected violations of this policy can be reported to <a href="mailto:support@poddispatch.com" className="text-primary hover:underline">support@poddispatch.com</a>.</p>
            </article>
          </TabsContent>

          <TabsContent value="clearinghouse">
            <article className="prose prose-sm dark:prose-invert max-w-none mt-6">
              <h2>PodDispatch Clearinghouse Disclaimer</h2>
              <p className="text-muted-foreground text-sm">Version 1.0 — Effective April 2026</p>

              <h3>PodDispatch Is Not a Clearinghouse</h3>
              <p>PodDispatch LLC is not a clearinghouse and is not a licensed billing service. The 837P EDI files generated by the platform are produced based on data entered by the operator and are intended for submission to a clearinghouse of the operator's choosing.</p>

              <h3>How Claim Submission Works</h3>
              <p>PodDispatch does not transmit claims directly to Medicare, Medicaid, or any other payer on behalf of operators. The exception is when an operator has independently configured a clearinghouse integration — for example, Office Ally — through their own trading partner agreement and credentials. In that configuration, PodDispatch transmits the operator-generated claim file to the operator's contracted clearinghouse on the operator's behalf. The clearinghouse, not PodDispatch, then forwards the claim to the appropriate payer.</p>

              <h3>No Warranty of Acceptance or Payment</h3>
              <p>PodDispatch LLC makes no warranty that generated claim files will be:</p>
              <ul>
                <li>Accepted by any clearinghouse or payer.</li>
                <li>Result in payment, partial payment, or any specific reimbursement amount.</li>
                <li>Free from errors attributable to incomplete or inaccurate data entry by the operator.</li>
                <li>Compliant with payer-specific edits, local coverage determinations, or state Medicaid rules that change without notice.</li>
              </ul>

              <h3>Operator Responsibilities</h3>
              <p>The operator is solely responsible for:</p>
              <ul>
                <li>Verifying claim accuracy before submission to any clearinghouse or payer.</li>
                <li>Maintaining their own provider enrollment, NPI credentials, Medicare/Medicaid enrollment, and any other licensure required to bill.</li>
                <li>Maintaining their own clearinghouse trading partner agreement and credentials.</li>
                <li>Complying with all payer-specific billing requirements, including modifier rules, prior authorization (UTN/RSNAT), timely filing limits, and signature-on-file requirements.</li>
                <li>Managing denials, corrected claims, secondary submissions, appeals, and resubmissions.</li>
                <li>Reconciling 835 remittance advice against the operator's general ledger.</li>
              </ul>

              <h3>PodDispatch's Limited Role</h3>
              <p>PodDispatch's role is limited to generating structured claim data from operator-entered documentation, applying ANSI X12 837P 5010A1 formatting, performing pre-submit validation against documented edits, and transmitting the resulting file when an operator-configured clearinghouse integration is enabled. PodDispatch does not adjudicate claims, does not provide coding advice, and does not act as a billing agent for the operator.</p>

              <h3>Contact</h3>
              <p>Questions about this disclaimer can be sent to <a href="mailto:support@poddispatch.com" className="text-primary hover:underline">support@poddispatch.com</a>.</p>
            </article>
          </TabsContent>

          <TabsContent value="retention">
            <article className="prose prose-sm dark:prose-invert max-w-none mt-6">
              <h2>PodDispatch Data Retention and Deletion Policy</h2>
              <p className="text-muted-foreground text-sm">Version 1.0 — Effective April 2026</p>

              <h3>Retention Period</h3>
              <p>PodDispatch LLC retains protected health information (PHI) and operator data for seven years following the date of service or account termination, whichever is later, in compliance with HIPAA and applicable state regulations.</p>

              <h3>Encryption at Rest</h3>
              <p>Electronic PHI is stored encrypted at rest using AES-256 encryption. All database storage, file storage, and backup storage are encrypted.</p>

              <h3>Backup Retention</h3>
              <p>Backup data is retained for 90 days on a rolling basis. Backups are encrypted using the same AES-256 standard as primary storage and are subject to the same access controls.</p>

              <h3>Audit Log Retention</h3>
              <p>Audit logs documenting PHI access events, administrative actions, login activity, billing actions, and data changes are retained for six years to satisfy HIPAA Security Rule audit requirements.</p>

              <h3>Account Termination — Export Window</h3>
              <p>Upon account termination, operators may request a data export within 30 days before deletion procedures begin. The export includes patient records, trip records, ePCRs, billing records, and audit logs in a structured format suitable for transfer to another system.</p>

              <h3>Deletion Requests</h3>
              <p>PHI deletion requests are processed within 60 days of receipt and confirmed in writing by PodDispatch LLC. Deletion requests can be submitted to <a href="mailto:support@poddispatch.com" className="text-primary hover:underline">support@poddispatch.com</a> by the owner-role user of the operator account.</p>

              <h3>Return or Destruction Under the BAA</h3>
              <p>PodDispatch LLC will return or destroy PHI as specified in the Business Associate Agreement upon termination of services where destruction is feasible and not prohibited by law.</p>

              <h3>Data That Cannot Be Destroyed</h3>
              <p>Data that cannot be destroyed due to legal hold, regulatory requirement, or backup infrastructure constraints will remain protected under the terms of the BAA, will continue to be encrypted at rest, and will not be used for any purpose other than compliance with the obligation that prevents its destruction.</p>

              <h3>Contact</h3>
              <p>Questions about data retention or deletion can be sent to <a href="mailto:support@poddispatch.com" className="text-primary hover:underline">support@poddispatch.com</a>.</p>
            </article>
          </TabsContent>

          <TabsContent value="incident">
            <article className="prose prose-sm dark:prose-invert max-w-none mt-6">
              <h2>PodDispatch Incident Response Policy</h2>
              <p className="text-muted-foreground text-sm">Version 1.0 — Effective April 2026</p>

              <h3>Purpose and Scope</h3>
              <p>PodDispatch LLC maintains a documented security incident response procedure in compliance with HIPAA Security Rule §164.308(a)(6). This policy applies to all suspected or confirmed security incidents involving the platform, its infrastructure, or PHI processed on behalf of operator companies.</p>

              <h3>Response Timeline</h3>
              <p>Upon discovery of a potential security incident involving PHI, PodDispatch LLC will:</p>
              <ul>
                <li><strong>Within 24 hours of discovery:</strong> Contain the incident by isolating affected systems, revoking compromised credentials, and stopping any active data exposure.</li>
                <li><strong>Within 10 business days of discovery:</strong> Complete a breach assessment under the HIPAA Breach Notification Rule (45 CFR §164.402) to determine whether unsecured PHI was acquired, accessed, used, or disclosed in a manner not permitted under HIPAA.</li>
                <li><strong>Within 60 days of discovery:</strong> Notify affected operator companies in writing of any confirmed breach.</li>
              </ul>

              <h3>Written Incident Report</h3>
              <p>For any confirmed breach, PodDispatch LLC will provide affected operators with a written incident report that includes:</p>
              <ul>
                <li>The nature of the breach and how it was discovered.</li>
                <li>The categories and approximate volume of PHI involved.</li>
                <li>The patients or records affected, to the extent identifiable.</li>
                <li>Steps taken to contain the breach and prevent further exposure.</li>
                <li>Recommended actions for the operator, including patient notification language.</li>
              </ul>

              <h3>Operator Responsibilities Following a Breach</h3>
              <p>Operators are responsible for:</p>
              <ul>
                <li>Notifying affected patients as required by 45 CFR §164.404.</li>
                <li>Notifying the Department of Health and Human Services as required by 45 CFR §164.408.</li>
                <li>Notifying media outlets if more than 500 individuals in a state or jurisdiction are affected, as required by 45 CFR §164.406.</li>
                <li>Maintaining their own breach log as required by HIPAA.</li>
              </ul>

              <h3>Post-Incident Review</h3>
              <p>PodDispatch LLC conducts a post-incident review following any confirmed breach, identifies root cause, implements corrective measures (technical controls, process changes, or workforce training), and documents the review in the company's compliance records.</p>

              <h3>Reporting a Suspected Incident</h3>
              <p>Security incidents — suspected or confirmed — can be reported to PodDispatch LLC by contacting support through the platform or by emailing <a href="mailto:support@poddispatch.com" className="text-primary hover:underline">support@poddispatch.com</a>. Please include the operator company name, a description of what was observed, the time of observation, and any system messages or screenshots if available.</p>
            </article>
          </TabsContent>
        </Tabs>

        <LegalFooter />
      </div>
    </div>
  );
}
