
-- Add PCR-specific columns to trip_records
ALTER TABLE public.trip_records
  ADD COLUMN IF NOT EXISTS pcr_status text NOT NULL DEFAULT 'not_started',
  ADD COLUMN IF NOT EXISTS attending_medic_id uuid REFERENCES public.profiles(id),
  ADD COLUMN IF NOT EXISTS attending_medic_name text,
  ADD COLUMN IF NOT EXISTS attending_medic_cert text,
  ADD COLUMN IF NOT EXISTS vitals_json jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS assessment_json jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS physical_exam_json jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS equipment_used_json jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS signatures_json jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS narrative text,
  ADD COLUMN IF NOT EXISTS pcr_completed_at timestamptz,
  ADD COLUMN IF NOT EXISTS pcr_submitted_by uuid REFERENCES public.profiles(id),
  ADD COLUMN IF NOT EXISTS condition_on_arrival jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS sending_facility_json jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS hospital_outcome_json jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS medications_json jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS procedures_json jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS iv_access_json jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS airway_json jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS crew_updated_fields jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS patient_position text,
  ADD COLUMN IF NOT EXISTS transport_condition text,
  ADD COLUMN IF NOT EXISTS chief_complaint text,
  ADD COLUMN IF NOT EXISTS primary_impression text,
  ADD COLUMN IF NOT EXISTS secondary_impressions jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS medical_necessity_reason text,
  ADD COLUMN IF NOT EXISTS level_of_consciousness text,
  ADD COLUMN IF NOT EXISTS skin_condition text,
  ADD COLUMN IF NOT EXISTS disposition text,
  ADD COLUMN IF NOT EXISTS at_scene_time timestamptz,
  ADD COLUMN IF NOT EXISTS patient_contact_time timestamptz,
  ADD COLUMN IF NOT EXISTS left_scene_time timestamptz,
  ADD COLUMN IF NOT EXISTS in_service_time timestamptz;
